# Generated by Django 5.1.5 on 2025-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_user_created_at_user_is_approve_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='weight_vote',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_vote',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
