# Generated by Django 5.1.5 on 2025-02-06 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_stability_departmentweight'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteevent',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_events', to='organisations.organisation'),
        ),
        migrations.CreateModel(
            name='VoteRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('vote_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_rounds', to='voting.voteevent')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRoundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_round_details', to=settings.AUTH_USER_MODEL)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_details', to=settings.AUTH_USER_MODEL)),
                ('vote_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_rounds', to='voting.voteround')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRoundUserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_reports', to=settings.AUTH_USER_MODEL)),
                ('vote_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_round_reports', to='voting.voteround')),
            ],
        ),
        migrations.DeleteModel(
            name='VoteDetails',
        ),
    ]
