# Generated by Django 5.1.5 on 2025-02-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_voteevent_organisation_voteround_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteround',
            name='stability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voterounddetails',
            name='estimation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='voterounduserreport',
            name='percent_bonus',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
