# Generated by Django 5.1.3 on 2024-12-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0002_alter_profile_start_work_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vote_events',
        ),
        migrations.RemoveField(
            model_name='votedetails',
            name='evaluated_employee',
        ),
        migrations.AddField(
            model_name='votedetails',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='skillpoint_api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votedetails',
            name='rated_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to='skillpoint_api.user'),
            preserve_default=False,
        ),
    ]
