# Generated by Django 5.1.3 on 2024-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0003_remove_user_vote_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteevent',
            name='end_day',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AddField(
            model_name='voteevent',
            name='frequency',
            field=models.CharField(blank=True, choices=[('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='voteevent',
            name='start_day',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='votedetails',
            name='estimation',
            field=models.FloatField(),
        ),
    ]
