# Generated by Django 5.1.3 on 2024-12-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0004_voteevent_end_day_voteevent_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skillpoint_api.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skillpoint_api.organisation'),
        ),
    ]
