# Generated by Django 5.1.3 on 2024-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0005_alter_department_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteevent',
            name='frequency',
            field=models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], default='month', max_length=10),
        ),
    ]
