# Generated by Django 5.1.3 on 2024-12-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0006_alter_voteevent_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedetails',
            name='vote_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_event', to='skillpoint_api.voteevent'),
        ),
    ]
