# Generated by Django 5.1.3 on 2024-12-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0008_alter_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillpoint_api.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillpoint_api.organisation'),
        ),
    ]
