# Generated by Django 5.1.5 on 2025-01-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillpoint_api', '0012_alter_user_options_user_unique_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
