# Generated by Django 5.1.5 on 2025-02-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stability',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=10),
        ),
        migrations.CreateModel(
            name='DepartmentWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_vote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('judge_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_weights', to='organisations.department')),
                ('rated_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_weights', to='organisations.department')),
            ],
        ),
    ]
